name: Workload PR Validation

on:
  workflow_call:
    inputs:
      databricks_host:
        description: "Databricks TEST workspace URL"
        required: false
        type: string
      warehouse_id:
        description: "Databricks TEST SQL warehouse ID"
        required: false
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  validate:
    runs-on: ubuntu-latest
    environment: platform-test

    env:
      DATABRICKS_CLIENT_ID: ${{ vars.DATABRICKS_CLIENT_ID }}
      DATABRICKS_AUTH_TYPE: github-oidc
      DATABRICKS_HOST: ${{ inputs.databricks_host }}

    steps:
      - name: Checkout PR
        uses: actions/checkout@v4

      - name: Skip bundle validation
        if: inputs.databricks_host == ''
        run: echo "Databricks TEST workspace does not currently exist."

      - name: Install Databricks CLI
        if: inputs.databricks_host != ''
        uses: databricks/setup-cli@main

      - name: Validate Databricks authentication
        if: inputs.databricks_host != ''
        run: databricks current-user me

      - name: Validate Databricks bundle
        working-directory: bundles/fraud
        if: inputs.databricks_host != ''
        env:
          BUNDLE_VAR_sql_warehouse_id: ${{ inputs.warehouse_id }}
        run: |
          databricks bundle validate -t test