name: Databricks Auth

on:
  workflow_call:

jobs:
  databricks-auth:
    runs-on: ubuntu-latest
    environment: dev

    env:
      DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ vars.DATABRICKS_CLIENT_ID }}
      DATABRICKS_AUTH_TYPE: github-oidc

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Test Databricks authentication
        run: databricks current-user me