name: Databricks CI

on:
  workflow_call:

jobs:
  databricks-ci:
    runs-on: ubuntu-latest
    environment: dev

    env:
      DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ vars.DATABRICKS_CLIENT_ID }}
      DATABRICKS_AUTH_TYPE: github-oidc

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Test Databricks authentication
        run: databricks current-user me

      - name: Validate Databricks bundle
        run: databricks bundle validate -t dev

      - name: Deploy Databricks bundle
        run: databricks bundle deploy -t dev

      - name: Run dbt build
        run: databricks bundle run dbt_transform_job -t dev --progress-format append